services:
  bsn-api:
    container_name: bsn-api
    image: rich210/bsn-api:1.0.5
    ports:
      - 8088:8088
    networks:
      - spring-demo
  bsn-ui:
    container_name: bsn-ui
    image: rich210/bsn-ui:0.0.1
    ports:
      - 80:4000
    networks:
      - spring-demo
    depends_on:
      - bsn-api
    environment:
      - API_URL=http://bsn-api:8088
networks:
  spring-demo:
    driver: bridge
volumes:
  postgres:
    driver: local