services:
  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.5
    ports:
      - 8088:8088
    networks:
      - spring-demo
  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:1.0.0
    ports:
      - 80:4000
    networks:
      - spring-demo
    depends_on:
      - bsn-api
    environment:
      - API_URL=http://bsn-api:8088
networks:
  spring-demo:
    driver: bridges